# 참조 : https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3"
services:
    nginx:     
        extends:
            file: ../../conf/env.yml
            service: default-config
        image: nginx:1.25.3-alpine
        container_name: nginx
        hostname: nginx
        user: "0:0" # root로 실행해야 한다.
        deploy:
            mode: replicated      
            replicas: 1           #전체에서 한개만 생성한다.
            restart_policy:
                condition: any  # on-failure or any
                delay: 5s
        environment:
            - TZ=Asia/Seoul
        ports:
            - 52001:52001
            - 80:80
            - 443:443
        volumes:
            - ./etc/nginx.conf:/etc/nginx/nginx.conf
            - ../../conf/ssl_wisevcs_co_kr:/etc/nginx/ssl
            - ../../../logs/nginx:/var/log/nginx
        restart: always
