# 참조 : https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3"
services:
    redis:
        extends:
            file: ../../conf/env.yml
            service: default-config
        # 참고 : https://hub.docker.com/_/redis
        image: redis:7.2
        command: /usr/local/etc/redis/redis.conf
        container_name: redis
        hostname: redis
        user: "0:0"
        deploy:
          mode: replicated      
          replicas: 1           #전체에서 한개만 생성한다.
          restart_policy:
            condition: any  # on-failure or any
            delay: 5s
        environment:
            - TZ=Asia/Seoul
        ports:
            - "56379:6379"
        volumes:
            - ./data:/usr/local/etc/redis
            - ../../../logs:/var/log/redis
        restart: always
